# Generated by Django 5.1.4 on 2025-01-09 07:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_profile_profpic_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://console.cloudinary.com/pm/c-524381c918b2075e676421d45f4da0/media-explorer?assetId=d1b906f294284f643f25ddede93a06ed', max_length=255, null=True, verbose_name='image'),
        ),
    ]
