# Generated by Django 5.1.4 on 2025-01-09 07:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/djenpeqlo/image/upload/f_auto,q_auto/v1/samples/balloons', max_length=255, null=True, verbose_name='image'),
        ),
    ]
