# Generated by Django 5.1.4 on 2025-01-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='photo',
        ),
    ]
